name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Tous les jours à minuit
  workflow_dispatch:       # Pour lancer manuellement

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # ← ton username auto (fredjacobbb)
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark

      - name: Deploy SVGs
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
